"""Build Dashboard/data/matches.js from Data/final_matches_cleaned.csv.

The dashboard ships its data as a small columnar JS file (loaded with a plain
<script> tag, so the page still works when opened straight from disk).
Run from the project root:  python tools/build-data.py
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "Data" / "final_matches_cleaned.csv"
OUT = ROOT / "Dashboard" / "data" / "matches.js"

# CSV column -> (output field, parser). Only fields the dashboard uses or may use.
def num(v):
    f = float(v)
    return int(f) if f.is_integer() else round(f, 2)

def opt_num(v):
    return None if v == "" else num(v)

def flag(v):
    return None if v == "" else v == "True"

FIELDS = [
    ("date", "date", str),
    ("team", "team", str),
    ("opponent", "opponent", str),
    ("venue", "venue", str),
    ("result", "result", str),
    ("gf", "gf", num),
    ("ga", "ga", num),
    ("xg", "xg", num),
    ("xga", "xga", num),
    ("poss", "poss", num),
    ("attendance", "attendance", opt_num),
    ("sh", "sh", num),
    ("sot", "sot", num),
    ("season", "season", num),
    ("matchweek_num", "matchweek_num", num),
    ("season_period", "season_period", str),
    ("points", "points", num),
    ("xg_diff", "xg_diff", num),
    ("high_scoring_flag", "high_scoring_flag", flag),
    ("low_attendance_flag", "low_attendance_flag", flag),
]
# Low-cardinality string columns are stored as indexes into a lookup list.
DICT_COLS = {"team", "opponent", "venue", "result", "season_period"}


def main():
    with SRC.open(encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))

    cols = {out: [] for _, out, _ in FIELDS}
    for r in rows:
        for src, out, parse in FIELDS:
            cols[out].append(parse(r[src]))

    dicts = {}
    for c in DICT_COLS:
        values = sorted(set(cols[c]))
        index = {v: i for i, v in enumerate(values)}
        dicts[c] = values
        cols[c] = [index[v] for v in cols[c]]

    payload = {"count": len(rows), "dicts": dicts, "cols": cols}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* Generated by tools/build-data.py from Data/final_matches_cleaned.csv — do not edit. */\n"
        "window.PL_MATCHES = " + json.dumps(payload, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} rows, {OUT.stat().st_size/1024:.0f} KB")


if __name__ == "__main__":
    main()
